### ISSUE TITLE
bond EPIC: x/sequencers cleanup unbonding / jail / slash

### ISSUE THREAD

**Issue by danwt** [dymensionxyz/dymension#1055]
With recent work relating to sequencer rotation, bond increase/decrease and jail and slash changes, the sequencer module needs to be improved.

This issue is a meta issue tracking other sub issues

## Nits

- [x] https://github.com/dymensionxyz/dymension/issues/1056
- [ ] https://github.com/dymensionxyz/dymension/issues/1057
- [ ] https://github.com/dymensionxyz/dymension/issues/1062

## Important

- [x] https://github.com/dymensionxyz/dymension/issues/1058
- [ ] https://github.com/dymensionxyz/dymension/issues/1059
- [ ] https://github.com/dymensionxyz/dymension/issues/1064
- [x] https://github.com/dymensionxyz/dymension/issues/1066
- [ ] https://github.com/dymensionxyz/dymension/issues/1067
- [ ] https://github.com/dymensionxyz/dymension/issues/1068
- [ ] https://github.com/dymensionxyz/dymension/issues/1069
- [x] https://github.com/dymensionxyz/dymension/issues/1071
- [ ] https://github.com/dymensionxyz/dymension/issues/1072

## Critical

- [x] https://github.com/dymensionxyz/dymension/issues/1060
- [x] https://github.com/dymensionxyz/dymension/issues/1061
- [ ] https://github.com/dymensionxyz/dymension/issues/1063
- [ ] https://github.com/dymensionxyz/dymension/issues/1065
- [x] https://github.com/dymensionxyz/dymension/issues/1070
- [ ] https://github.com/dymensionxyz/dymension/issues/1255
- [ ] https://github.com/dymensionxyz/dymension/issues/1257

## Urgent/Blocking

- [x] https://github.com/dymensionxyz/dymension/issues/1073

**Comment by danwt** [comment]
I've assigned @spoo-bar but there are relevant things for myself and @mtsitrin (https://github.com/dymensionxyz/dymension/issues/1071) (https://github.com/dymensionxyz/dymension/issues/1066)

**Comment by danwt** [comment]
superseded by https://github.com/dymensionxyz/dymension/issues/1328
